language: rust
rust:
  - stable
install:
  - rustup toolchain install nightly-2019-10-13
  - rustup component add rustfmt --toolchain nightly-2019-10-13
  - rustup component add clippy --toolchain nightly-2019-10-13
before_script:
  - cargo fetch --verbose
script:
  - cargo +nightly-2019-10-13 fmt -- --check
  - cargo +nightly-2019-10-13 clippy --all --all-targets -- -D warnings
  - RUST_BACKTRACE=1 cargo test --verbose
matrix:
  include:
    - os: linux
    - os: osx
cache: cargo
git:
  depth: 1
